services:
    nginx:
        image: nginx:stable
        ports:
            - '8080:80'
        volumes:
            - ./laravel:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - '9000:9000'
    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=pocadi
            - MYSQL_PASSWORD=pocadi123
            - MYSQL_ROOT_PASSWORD=pocadi123
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8081:80'
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=pocadi
            - PMA_PASSWORD=pocadi123